name: Run tests
run-name: ${{ github.actor }} is running tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install millipds python module
        run: |
          python3 -m pip install .[test]
      - name: Run pyright type checking
        run: |
          python3 -m pyright src/millipds/
      - name: Run the tests
        run: |
          python3 -m pytest tests/
